# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eef491d0ef35320672a4178c492887d01179b13008e87c950c5e889d7fc3bb80b7ce7c2a69d4d81c13ac0ffe7658c0ef7dc94ae47aeb97a6f26c75fac1fb3114

test:
  secret_key_base: f1e4cea65e72646a8b7acde2e557703fe46fc2dec2ff9fedec4707c798821074f91327b2921b702242b18845e6af6895f752e6eb410638acb94481d3b27f2736

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
